name: Update blocklists

on:
  push:
    paths:
      - 'sources/**.txt'
      - 'filters/**.txt'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run update
      run: ./scripts/update.sh

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git commit -m "Update blocklists"; then
          git push
        fi